### ISSUE TITLE
If a nickname is same as a directory name in pwd, goto takes you to the immediate directory instead of the nicknamed directory

### ISSUE THREAD

**Issue by shreyagarge** [justagist/.justabash#2]
sgarge-Mac:~ $ mydir -l

         -- My Directories List --
    .
    . 
    10	 gatling  ~~##~~  /Users/sgarge/faas/fn-gatling
    .
    .

Expected behaviour:
     ` sgarge-Mac:~ $ goto gatling`
should result in 
    `  sgarge-Mac:/Users/sgarge/faas/fn-gatling $ `

Observed behaviour:
     `sgarge-Mac:~ $ goto gatling`
results in 
    ` sgarge-Mac:gatling $ `

Reason:
There is a directory with the same name "gatling" as the nickname in `~`.

**Comment by justagist** [comment]
That is a bug. Will fix it in the next update!

**Comment by justagist** [comment]
Fixed in latest update!
